// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarTEDDb.Entities;

[Index("EmployeeID", Name = "IX_EmployeeID")]
public partial class Club
{
    [Key]
    [StringLength(10, ErrorMessage = "Club ID cannot be more than 10 characters.")]
    [Unicode(false)]
    public string ClubID { get; set; }

    [Required(ErrorMessage = "Club Name cannot be empty.")]
    [StringLength(50, ErrorMessage = "Club Name cannot be more than 50 characters.")]
    [Unicode(false)]
    public string ClubName { get; set; }

    public bool Active { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "money")]
    public decimal Fee { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Clubs")]
    public virtual Employee Employee { get; set; }
}